about_page = """Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam at finibus arcu. Suspendisse rhoncus dolor purus, non molestie mauris finibus vitae. Nulla pulvinar iaculis enim eget fermentum. Etiam ornare mauris non eros posuere gravida ut quis justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec eu pellentesque sem. Nunc dignissim enim eu convallis ultrices. Etiam rutrum mauris ut lacinia commodo. Vestibulum molestie, felis venenatis pulvinar aliquam, quam est blandit dui, vitae luctus velit eros sed dui. Suspendisse id nunc varius, eleifend lacus efficitur, feugiat mi. Nunc sit amet dictum tellus, vel sollicitudin dolor. Suspendisse potenti. Aenean leo odio, semper at metus gravida, faucibus cursus dolor. Praesent metus metus, commodo sit amet diam vel, bibendum consequat diam. Cras justo sapien, viverra eu porta at, tincidunt varius nibh.

Donec eu sapien id arcu imperdiet ullamcorper. Morbi ipsum purus, vulputate in pellentesque convallis, molestie ac tortor. Donec id libero malesuada, rhoncus justo et, consequat felis. Nullam bibendum ut nibh eu scelerisque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus hendrerit felis a fringilla porta. Aenean nec consequat metus, ut sollicitudin dolor. Quisque faucibus consectetur maximus. Donec sed enim dui. Donec facilisis a leo vitae consequat. Quisque id convallis dolor, at facilisis sem. Vivamus leo orci, finibus ornare rutrum sit amet, sodales sed lectus. Proin vel porttitor risus, at vulputate nulla. Sed ultrices vel orci vitae volutpat. Donec tortor justo, posuere ut nunc quis, cursus auctor felis. Etiam egestas urna vel mi semper vestibulum."""

regression_ml_introduction = """Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed aliquet ante eu malesuada tincidunt. Ut eleifend, arcu finibus semper suscipit, dui lorem scelerisque felis, et fermentum ex urna id est. Nulla rhoncus lectus lectus, et faucibus enim auctor et. Nunc sit amet semper neque. Donec lacinia nec ex at imperdiet. Donec lacus ligula, congue in viverra molestie, venenatis fringilla est. Phasellus sodales sed lectus a vestibulum.

Proin elit ipsum, ultricies quis risus vitae, auctor aliquam sapien. Maecenas vulputate pretium metus sit amet aliquet. Suspendisse vehicula erat id sodales efficitur. Duis ultrices auctor libero, ac fermentum neque dignissim vel. Integer quam nunc, aliquet a enim sit amet, efficitur rhoncus quam. Donec maximus nisl ut faucibus rutrum. Quisque tristique urna mauris, ut scelerisque turpis aliquet eu. Morbi sem neque, dapibus et elit eget, mollis iaculis lacus. Suspendisse potenti."""

regression_gd_explain = """Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed aliquet ante eu malesuada tincidunt. Ut eleifend, arcu finibus semper suscipit, dui lorem scelerisque felis, et fermentum ex urna id est. Nulla rhoncus lectus lectus, et faucibus enim auctor et. Nunc sit amet semper neque. Donec lacinia nec ex at imperdiet. Donec lacus ligula, congue in viverra molestie, venenatis fringilla est. Phasellus sodales sed lectus a vestibulum.

Proin elit ipsum, ultricies quis risus vitae, auctor aliquam sapien. Maecenas vulputate pretium metus sit amet aliquet. Suspendisse vehicula erat id sodales efficitur. Duis ultrices auctor libero, ac fermentum neque dignissim vel. Integer quam nunc, aliquet a enim sit amet, efficitur rhoncus quam. Donec maximus nisl ut faucibus rutrum. Quisque tristique urna mauris, ut scelerisque turpis aliquet eu. Morbi sem neque, dapibus et elit eget, mollis iaculis lacus. Suspendisse potenti."""

regression_gde_explain = """Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed aliquet ante eu malesuada tincidunt. Ut eleifend, arcu finibus semper suscipit, dui lorem scelerisque felis, et fermentum ex urna id est. Nulla rhoncus lectus lectus, et faucibus enim auctor et. Nunc sit amet semper neque. Donec lacinia nec ex at imperdiet. Donec lacus ligula, congue in viverra molestie, venenatis fringilla est. Phasellus sodales sed lectus a vestibulum.

Proin elit ipsum, ultricies quis risus vitae, auctor aliquam sapien. Maecenas vulputate pretium metus sit amet aliquet. Suspendisse vehicula erat id sodales efficitur. Duis ultrices auctor libero, ac fermentum neque dignissim vel. Integer quam nunc, aliquet a enim sit amet, efficitur rhoncus quam. Donec maximus nisl ut faucibus rutrum. Quisque tristique urna mauris, ut scelerisque turpis aliquet eu. Morbi sem neque, dapibus et elit eget, mollis iaculis lacus. Suspendisse potenti."""

regression_ols_explain = """Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed aliquet ante eu malesuada tincidunt. Ut eleifend, arcu finibus semper suscipit, dui lorem scelerisque felis, et fermentum ex urna id est. Nulla rhoncus lectus lectus, et faucibus enim auctor et. Nunc sit amet semper neque. Donec lacinia nec ex at imperdiet. Donec lacus ligula, congue in viverra molestie, venenatis fringilla est. Phasellus sodales sed lectus a vestibulum.

Proin elit ipsum, ultricies quis risus vitae, auctor aliquam sapien. Maecenas vulputate pretium metus sit amet aliquet. Suspendisse vehicula erat id sodales efficitur. Duis ultrices auctor libero, ac fermentum neque dignissim vel. Integer quam nunc, aliquet a enim sit amet, efficitur rhoncus quam. Donec maximus nisl ut faucibus rutrum. Quisque tristique urna mauris, ut scelerisque turpis aliquet eu. Morbi sem neque, dapibus et elit eget, mollis iaculis lacus. Suspendisse potenti."""

regression_polinomial_explain = """Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed aliquet ante eu malesuada tincidunt. Ut eleifend, arcu finibus semper suscipit, dui lorem scelerisque felis, et fermentum ex urna id est. Nulla rhoncus lectus lectus, et faucibus enim auctor et. Nunc sit amet semper neque. Donec lacinia nec ex at imperdiet. Donec lacus ligula, congue in viverra molestie, venenatis fringilla est. Phasellus sodales sed lectus a vestibulum.

Proin elit ipsum, ultricies quis risus vitae, auctor aliquam sapien. Maecenas vulputate pretium metus sit amet aliquet. Suspendisse vehicula erat id sodales efficitur. Duis ultrices auctor libero, ac fermentum neque dignissim vel. Integer quam nunc, aliquet a enim sit amet, efficitur rhoncus quam. Donec maximus nisl ut faucibus rutrum. Quisque tristique urna mauris, ut scelerisque turpis aliquet eu. Morbi sem neque, dapibus et elit eget, mollis iaculis lacus. Suspendisse potenti."""